version: 0.2
 
phases:
  pre_build:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      #- "$(aws ecr get-login --region us-east-1 )"
      - "$(aws ecr get-login-password --region us-east-1)"
      #- REPOSITORY_URI=411859375163.dkr.ecr.us-east-1.amazonaws.com/nodejs
      
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - "docker build -t nodejs ."
      - "docker tag nodejs:latest 411859375163.dkr.ecr.us-east-1.amazonaws.com/nodejs:latest"      
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 411859375163.dkr.ecr.us-east-1.amazonaws.com/nodejs:latest"
